version: 2
jobs:
  build:
    docker:
      - image: cimg/go:1.21
    steps:
      - checkout
      - run: sudo apt update
      - run: sudo apt install libsdl2-dev
      - run: go get -d ./...
      - run: go test ./...
